name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Connect deploy key
#         uses: cloudtype-github-actions/connect@v1
#         with:
#           token: ${{ secrets.CLOUDTYPE_TOKEN }}
#           ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: dntjd1097/responsive-slack-bot
          stage: main
          yaml: >
            name: responsive-slack-bot

            app: python@3.9

            options:
              env:
                - name: FLASK_ENV
                  value: production
                - name: SLACK_BOT_TOKEN
                  value: ${{ secrets.SLACK_BOT_TOKEN }}
                - name: SLACK_APP_TOKEN
                  value: ${{ secrets.SLACK_APP_TOKEN }}
              start: python slack.py
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
